### ISSUE TITLE
./configure --with-hfst --without-xfst

### ISSUE THREAD

**Issue by rueter** [giellalt/lang-sms#1]
When running
          ../configure --disable-hfst-desktop-spellers --enable-spellers --enable-fst-hyphenator --enable-hfst-mobile-speller
sms virtually requires: ```--with-hfst --without-xfst --enable-reversed-intersect ```
without specifically selecting hfst and deselecting xfst, and without reversed intersect,
the time required for a successful compilation of approx. 13 minutes may rise to nearly one hour.

**Comment by snomos** [comment]
This has been fixed in commit 49a52553. Hfst is default, reversed intersect is default, and the foma backend is default. Should make for as fast an hfst compilation as possible. You can change the defaults for SMS only by editing the `configure.ac` file.
