### ISSUE TITLE
Stray character +U02BC "ʼ" introduced in hfst output of sms analysis (Bugzilla Bug 2652)

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-sms#13]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2652
Date: 2020-03-19T04:49:41+01:00
From: Jack Rueter &lt;<rueter.jack>&gt;
To:   Sjur Nørstebø Moshagen &lt;<sjur.n.moshagen>&gt;
CC:   borre.gaup, chiara.argese

Last updated: 2020-03-19T04:49:41+01:00

**Comment by albbas** [comment]
## Comment 13858
Date: 2020-03-19 04:49:41 +0100
From: Jack Rueter &lt;<rueter.jack>&gt;

When applying the pipeline
hfst-tokenise --giella-cg -W $GTHOME/langs/sms/tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 -g $GTHOME/langs/sms/src/syntax/disambiguator.cg3 

to the sms text:
'De suu teâđast ... son käggõõđi teä suu koʹdde, pačču di koʹdde.'

undesired output occurs in the form of introduced Modifier Letter Apostrophe +U02BC. (This is one of the characters in the sms orthography.)

"<De>"
	"de" Adv Sem/Time 
	"de" CC 
: 
"<suu>"
	"son" Pron Pers Sg3 Acc 
	"son" Pron Pers Sg3 Gen
: 
"<teâđast>"
	"teâtt" N Sg Loc
	"teâđast" Adv 
	"teâđsted" V Ind Prs Sg3 
: 
"<...>"
	"..." CLB

"<>"
	"ʼ" N Symbol
: 
"<son>"
	"son" Pron Pers Sg3 Nom
: 
"<käggõõđi>"
	"käggõõđi" ?
: 
"<teä>"
	"teä" Adv Sem/Time Sem/Time 
: 
"<suu>"
	"son" Pron Pers Sg3 Acc 
	"son" Pron Pers Sg3 Gen
: 
"<koʹdde>"
	"kåʹdded" V Ind Prt Pl3 
"<,>"
	"," CLB
"<>"
	"ʼ" N Symbol
: 
"<pačču>"
	"pääččad" V Ind Prt Pl3 
: 
"<di>"
	"di" CC 
: 
"<koʹdde>"
	"kåʹdded" V Ind Prt Pl3 
"<.>"
	"." CLB

"<>"
	"ʼ" N Symbol
:\n
"<>"
	"ʼ" N Symbol

In the analysis epsilon has become Modifier Letter Apostrophe +U02BC in seemingly random places.

One workaround is to comment "Modifier Letter Apostrophe +U02BC" out in the 
"src/morphology/generated_files/symbols.lexc" file locally.

This immediately disallows the unwanted output. Of course, the introduction of the Modifier Letter Apostrophe might be associated with the spellrelax in:
ʼ (->) 0 ,  # U+02BC MODIFIER LETTER APOSTROPHE, accept also ZERO.

Should native symbols be removed or commented out of the symbols.lexc?

**Comment by rueter** [comment]
The life of the issue shows the following:
```
 echo 'De suu teâđast ... son käggõõđi teä suu koʹdde, pačču di koʹdde.' | hfst-tokenise --giella-cg -W $GTHOME/lang-sms/tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 -g $GTHOME/lang-sms/src/cg3/disambiguator.cg3
"<De>"
	"de" Adv <sms> @ADVL>
	"de" CC <sms>
: 
"<suu>"
	"son" Pron <sms> Pers Sg3 Acc
	"son" Pron <sms> Pers Sg3 Gen
: 
"<teâđast>"
	"teâtt" N <sms> Sg Loc
	"teâđsted" V <sms> Ind Prs Sg3 @+FMAINV
	"teâđast" Adv <sms>
: 
"<...>"
	"..." CLB
: 

"<son>"
	"son" Pron <sms> Pers Sg3 Nom @SUBJ>
: 
"<käggõõđi>"
	"käggõõttâd" V <sms> Ind Prt Sg3 @+FMAINV
: 
"<teä>"
	"teä" Adv <sms> Sem/Time Sem/Time @ADVL>
: 
"<suu>"
	"son" Pron <sms> Pers Sg3 Acc
	"son" Pron <sms> Pers Sg3 Gen
: 
"<koʹdde>"
	"kåʹdded" V <sms> Ind Prt Pl3 @+FMAINV
"<,>"
	"," CLB
: 
"<pačču>"
	"pääččad" V <sms> Imprt ConNegII @+FMAINV
: 
"<di>"
	"di" CC <sms> @CVP
: 
"<koʹdde>"
	"kåʹdded" V <sms> Ind Prt Pl3 @+FMAINV
"<.>"
	"." CLB
:\n


```
There are no longer U+02BC MODIFIER LETTER APOSTROPHE introductions.
This can be closed.
