### ISSUE TITLE
Add missing affixes/acronyms.lexc

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-sms#2]
SMS fails in Tino's nightlies, and the reason is a missing contlex for acronyms, cf https://apertium.projectjj.com/apt/logs/giella-sms/sid-amd64.log (@TinoDidriksen for info).

It turns out that SMS does not have an affix file for acronyms at all, as opposed to all other SMx repos. One could probably just copy e.g. from SMN or SME, and adjust the continuations according to the needs of SMS.

**Comment by Trondtr** [comment]
Jaska has added affixes/acronyms.lexc from smn (log says sme, but header is smn). sms still does not build, so I keep the bug open until we know the missing build is for some other reason.

**Comment by snomos** [comment]
Whatever was done, it seems to build fine now.
