### ISSUE TITLE
Error: The file lexicon.tmp.lexc did not compile cleanly

### ISSUE THREAD

**Issue by carges** [giellalt/lang-sms#3]
I get an error when trying to compile.
If I run make V=1, I get the following:
```
...
N_Prop_Toponyms_sms2x...400 Num_sms2x...91 Pcle_sms2x...31 Prefix_sms2x...36 Pron_sms2x...47 V_sms2x...5133 ABBR_sms2x...105 ACRO_sms2x...11 Punctuation...60 PunctEnd...1 Symbols...Compiling... Warning: Sublexicon is mentioned but not defined. (OY-sur) 
*** ERROR: could not parse lexc file: treating warnings as errors [--Werror] ***
/usr/local/bin/hfst-lexc: The file lexicon.tmp.lexc did not compile cleanly.
(if there are no error messages above, try -v or -d to get more info)
make[2]: *** [lexicon.tmp.hfst] Error 1
make[2]: *** Deleting file `lexicon.tmp.hfst'
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by snomos** [comment]
The problem is that the lexc code isn't clean. @rueter or @Trondtr might know something.

**Comment by Trondtr** [comment]
IYes, that is true. OY-sur was commentec out, I'll comment it in again.

Trond

Trond Trosterud
Giellatekno, UiT Noregs arktiske universitet
trond.trosterud@uit.n
0047 776 44763

________________________________________
Lähettäjä: Chiara Argese <notifications@github.com>
Lähetetty: keskiviikko 6. tammikuuta 2021 16.06
Vastaanottaja: giellalt/lang-sms
Kopio: Subscribed
Aihe: [giellalt/lang-sms] Error: The file lexicon.tmp.lexc did not compile cleanly (#3)

I get an error when trying to compile.
If I run make V=1, I get the following:

...
N_Prop_Toponyms_sms2x...400 Num_sms2x...91 Pcle_sms2x...31 Prefix_sms2x...36 Pron_sms2x...47 V_sms2x...5133 ABBR_sms2x...105 ACRO_sms2x...11 Punctuation...60 PunctEnd...1 Symbols...Compiling... Warning: Sublexicon is mentioned but not defined. (OY-sur)
*** ERROR: could not parse lexc file: treating warnings as errors [--Werror] ***
/usr/local/bin/hfst-lexc: The file lexicon.tmp.lexc did not compile cleanly.
(if there are no error messages above, try -v or -d to get more info)
make[2]: *** [lexicon.tmp.hfst] Error 1
make[2]: *** Deleting file `lexicon.tmp.hfst'
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by carges** [comment]
Thanks @Trondtr, now compilation is successful!
