### ISSUE TITLE
System-wide speller suggests what it does not accept in TextEdit MacOS

### ISSUE THREAD

**Issue by rueter** [giellalt/lang-sms#8]
On 13.5.1 Ventura the spell checker does not accept word forms like ‹säämas›, but its top suggestion is the very same ‹säämas› form. This is related to https://github.com/giellalt/lang-lut/issues/4 and, most likely, https://github.com/giellalt/lang-lut/issues/1
```
hfst-lookup src/fst/analyser-gt-norm.hfstol 
> säämas
säämas	säämas+Adv	0,000000
säämas	sääʹmm+N+Lat	0,000000

echo 'säämas' | hfst-tokenise -g tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<säämas>"
	"säämas" Adv <W:0.0>
	"sääʹmm" N Sem/Hum Lat <W:0.0>

hfst-ospell -S -n 5 tools/spellcheckers/sms.zhfst 
säämas
"säämas" is in the lexicon...

```
BUT, it is not accepted by the speller.

<img width="908" alt="Screenshot 2024-01-30 at 12 18 13" src="https://github.com/giellalt/lang-sms/assets/14276164/4e5bc8ea-060f-4c45-8456-75c28a7ee4d2">

**Comment by snomos** [comment]
Can you please post a bit more of the text into this issue, *exactly as it is written in the editor*? Preferably a whole sentence or paragraph that includes the word in question.

This also goes for the other bug reports that you mention (for lut).

**Comment by snomos** [comment]
Updated information:

> but I found the sms bug was not repeating itself very well for me.
> Good news: few problems in sms

Thus closing this one.
